apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkin-new.fullname" . }}
  labels:
    {{- include "jenkin-new.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    {{- include "jenkin-new.selectorLabels" . | nindent 4 }}
