apiVersion: cert-manager.io/v1  
kind: ClusterIssuer
metadata:
  name: encryp-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - http01:
        ingress:
          class: nginx
    # - dns01:
    #     cloudflare:
    #       email: ziwakorn.j@gmail.com
    #       apiKeySecretRef:
    #         name: cloudflare-api-key-secret
    #         key: api-key
---
apiVersion: cert-manager.io/v1  
kind: ClusterIssuer
metadata:
  name: encryp-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

